esphome:
  name: solarpanel-switch
  friendly_name: Solarpanel-switch

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HkLUx6XV1eWLIezYo7hj9dncWWov2+Sv49YSyr7dSik="

ota:
  - platform: esphome
    password: "1c167bd760d1c35cb6f25350dfe6d85f"

wifi:
  ssid: "BirdsBoven"
  password: "Highway12!"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EspHome Hotspot"
    password: "1234567890"


captive_portal:


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Wifi Info: IP Address"
    ssid:
      name: "Wifi Info: SSID"
    bssid:
      name: "Wifi Info: BSSID"
    mac_address:
      name: "Wifi Info: MAC Address"
    dns_address:
      name: "Wifi Info: DNS Address"

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: uptime
    name: 'Uptime'
    update_interval: 15s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 15s

#output:
#  - platform: gpio
#    pin: 4
#    id: string_1

#  - platform: gpio
#    pin: 6
#    id: string_2

switch:
  - platform: gpio
    pin: 4
    name: "string_1"

  - platform: gpio
    pin: 6
    name: "string_2"